# Pandas Challenges

####  Challenge 1 – Complete Data Cleaning
####  Your manager gives you a messy dataset.
####  Perform all of the following:
####  • Load the dataset.
#### • Display dataset information.
####  • Find missing values.
####  • Remove duplicate rows.
####  • Fill missing values:
####  o Age → median
####  o Balance → mean
####  • Rename:
####  o Target → CustomerStatus
####  o AnnualIncome → Income
####  • Display the first 15 rows.
####  Methods expected:
####  read_csv()
####  info()
####  isnull()
####  drop_duplicates()
####  median()
####  mean()
####  fillna()
#### rename()
####  head()

In [24]:
import pandas as pd

df=pd.read_csv("C:\\Users\\ywako\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [25]:
print("Dataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

df = df.drop_duplicates()

df["Age"] = df["Age"].fillna(df["Age"].median())

df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

df = df.rename(columns={
    "Target": "CustomerStatus",
    "AnnualIncome": "Income"
})

df.head(15)

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

Missing Values:
CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

C:\Users\ywako\AppData\Local\Temp\ipykernel_10904\936830522.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].fillna(df["Age"].median())
C:\Users\ywako\AppData\Local\Temp\ipykernel_10904\936830522.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,97557.565779,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn
10,10011,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn

#### Challenge 2 – Banking Report
#### The bank wants a numeric report.
#### Tasks
#### • Select only numeric columns.
#### • Display summary statistics.
#### • Convert Age and CreditScore to float.
#### • Display information again.

In [20]:
numeric_df = df.select_dtypes(include=["number"])

print("Numeric Columns:")
print(numeric_df)

print("\nSummary Statistics:")
print(numeric_df.describe())

df["Age"] = df["Age"].astype(float)
df["CreditScore"] = df["CreditScore"].astype(float)

df.info()

Numeric Columns:
     CustomerID   Age    Income  Spending  CreditScore        Balance  Tenure
0         10001  58.0   49184.0      2139          581   97557.565779       2
1         10002  65.0  162964.0      6197          732    6356.540000       1
2         10003  56.0   26956.0     37281          503  143203.920000       8
3         10004  55.0   92926.0       925          463  139627.880000       5
4         10005  66.0  108236.0      7198          394   75985.460000       5
..          ...   ...       ...       ...          ...            ...     ...
995       10996  34.0   81731.0     40980          761  181465.650000       5
996       10997  47.0   42475.0      1176          780   26640.990000       5
997       10998  31.0  120531.0     46929          733  147220.820000       4
998       10999  21.0   33661.0     22314          540   94186.480000       5
999       11000  63.0   31930.0       851          559  100908.400000       6

[1000 rows x 7 columns]

Summary Statistics:
         CustomerID          Age         Income      Spending  CreditScore  \
count   1000.000000  1000.000000     950.000000   1000.000000  1000.000000
mean   10500.500000    44.202000  112458.303158  25285.558000   603.088000
std      288.819436    15.130834   52409.868404  14211.735656   176.605486
min    10001.000000    18.000000   20227.000000    537.000000   300.000000
25%    10250.750000    31.000000   65922.500000  13213.000000   441.000000
50%    10500.500000    44.000000  112347.500000  24901.000000   606.500000
75%    10750.250000    57.000000  157973.000000  37960.250000   758.250000
max    11000.000000    70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count    1000.000000  1000.000000
mean    97557.565779     5.241000
std     54430.062006     3.179155
min       547.600000     0.000000
25%     52074.240000     2.000000
50%     97557.565779     5.000000
75%    142297.910000     8.000000
max    199885.880000    10.000000
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1000 non-null   int64
 1   Age             1000 non-null   float64
 2   Income          950 non-null    float64
 3   Spending        1000 non-null   int64
 4   CreditScore     1000 non-null   float64
 5   Balance         1000 non-null   float64
 6   Tenure          1000 non-null   int64
 7   Geography       950 non-null    object
 8   Gender          950 non-null    object
 9   Segment         950 non-null    object
 10  CustomerStatus  1000 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 93.8+ KB

#### Challenge 3 – Duplicate Investigation
#### Find duplicate customers. Then
#### • Count duplicate rows.
#### • Remove duplicates.
#### • Print information before and after removing duplicates.
#### • Show the last 20 rows.

In [21]:
print("Information BEFORE removing duplicates:")
df.info()

duplicates = df[df.duplicated()]

print("\nDuplicate Rows:")
print(duplicates)

duplicate_count = df.duplicated().sum()

print("\nNumber of Duplicate Rows:", duplicate_count)

df = df.drop_duplicates()

df.info()

Information BEFORE removing duplicates:
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1000 non-null   int64
 1   Age             1000 non-null   float64
 2   Income          950 non-null    float64
 3   Spending        1000 non-null   int64
 4   CreditScore     1000 non-null   float64
 5   Balance         1000 non-null   float64
 6   Tenure          1000 non-null   int64
 7   Geography       950 non-null    object
 8   Gender          950 non-null    object
 9   Segment         950 non-null    object
 10  CustomerStatus  1000 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 93.8+ KB

Duplicate Rows:
Empty DataFrame
Columns: [CustomerID, Age, Income, Spending, CreditScore, Balance, Tenure, Geography, Gender, Segment, CustomerStatus]
Index: []

Number of Duplicate Rows: 0
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1000 non-null   int64
 1   Age             1000 non-null   float64
 2   Income          950 non-null    float64
 3   Spending        1000 non-null   int64
 4   CreditScore     1000 non-null   float64
 5   Balance         1000 non-null   float64
 6   Tenure          1000 non-null   int64
 7   Geography       950 non-null    object
 8   Gender          950 non-null    object
 9   Segment         950 non-null    object
 10  CustomerStatus  1000 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 93.8+ KB

#### Challenge 4 – HR Department
#### HR wants better column names.
#### Rename
#### CustomerID → Employee_ID
#### Age → EmployeeAge
#### Gender → EmployeeGender
#### AnnualIncome → Salary
#### Target → PromotionStatus
#### Then
#### • Add prefix
#### HR_
#### to every column.
#### Display 10 random records.

In [22]:
df = df.rename(columns={
    "CustomerID": "Employee_ID",
    "Age": "EmployeeAge",
    "Gender": "EmployeeGender",
    "AnnualIncome": "Salary",
    "Target": "PromotionStatus"
})

df = df.add_prefix("HR_")

df.sample(10)

,HR_Employee_ID,HR_EmployeeAge,HR_Income,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Segment,HR_CustomerStatus
511,10512,25.0,116099.0,47103,338.0,75038.49,10,UK,Other,SME,Churn
713,10714,53.0,181479.0,48712,836.0,49249.17,1,UK,Female,Corporate,Churn
356,10357,24.0,87826.0,15049,822.0,149370.61,8,Germany,Other,SME,Stay
585,10586,39.0,145817.0,30833,756.0,71748.32,4,Canada,Other,Retail,Stay
850,10851,28.0,174938.0,4691,408.0,22835.94,9,Germany,Male,Retail,Churn
676,10677,30.0,NaN,3913,523.0,194654.81,3,France,NaN,Corporate,Stay
960,10961,36.0,89508.0,3615,604.0,199245.54,6,USA,Other,SME,Stay
728,10729,27.0,109597.0,26245,440.0,17559.00,6,Germany,Other,SME,Churn
447,10448,69.0,54207.0,22831,481.0,183756.16,5,India,Male,Retail,Churn
687,10688,30.0,157381.0,45275,809.0,153146.82,2,Germany,Female,NaN,Stay

#### Challenge 5 – Finance Cleaning
#### Finance department reports missing values.
#### Tasks
#### Fill
#### AnnualIncome → Median
#### Balance → Mean
#### Age → Median
#### Then
#### Generate descriptive statistics.

In [12]:
df["HR_Income"] = df["HR_Income"].fillna( df["HR_Income"].median())

df["HR_Balance"] = df["HR_Balance"].fillna(df["HR_Balance"].mean())

df["HR_EmployeeAge"] = df["HR_EmployeeAge"].fillna(df["HR_EmployeeAge"].median())

print("Descriptive Statistics:")
df.describe()

Descriptive Statistics:

,HR_Employee_ID,HR_EmployeeAge,HR_Income,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,10500.500000,44.202000,112452.763000,25285.558000,603.088000,97557.565779,5.241000
std,288.819436,15.130834,51081.480963,14211.735656,176.605486,54430.062006,3.179155
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10250.750000,31.000000,68437.250000,13213.000000,441.000000,52074.240000,2.000000
50%,10500.500000,44.000000,112347.500000,24901.000000,606.500000,97557.565779,5.000000
75%,10750.250000,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

#### Challenge 6 – Data Type Audit
#### The company says
#### Age and AnnualIncome are stored incorrectly.
#### Tasks
#### Convert
#### Age → int
#### AnnualIncome → float
#### Balance → float
#### Target → string
#### Print information.

In [23]:
df["Age"] = df["Age"].astype(int)
df["AnnualIncome"] = df["AnnualIncome"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df["Target"] = df["Target"].astype(str)

print("Dataset Information:")
df.info()

KeyError: 'Age'